

function on_game_start()
	RegisterScriptCallback("on_specific_character_dialog_list", function(character_id, dialog_list)
	
		if character_id == "jup_depo_isg_tech" then
			local res = dialog_list:add("aftermarket_exchange_insider_mercenary")
		end
		
		if character_id == "pri_monolith_monolith_mechanic_stalker" then
			local res = dialog_list:add("aftermarket_exchange_insider_monolith")
		end
		
		if character_id == "pri_a16_mech_mlr" then
			local res = dialog_list:add("aftermarket_exchange_insider_loner")
		end
		
		if character_id == "mechanic_monolith_kbo" then
			local res = dialog_list:add("aftermarket_exchange_insider_monolith")
		end
		
		if character_id == "merc_pri_a18_mech_mlr" then
			local res = dialog_list:add("aftermarket_exchange_insider_mercenary")
		end
		
		if character_id == "mechanic_army_yan_mlr" then
			local res = dialog_list:add("aftermarket_exchange_insider_ecolog")
		end
		
		if character_id == "red_forester_tech" then
			local res = dialog_list:add("aftermarket_exchange_insider_loner")
		end
		
		if character_id == "red_greh_tech" then
			local res = dialog_list:add("aftermarket_exchange_insider_monolith")
		end
		
		if character_id == "mil_smart_terrain_7_7_freedom_mechanic_stalker" then
			local res = dialog_list:add("aftermarket_exchange_insider_freedom")
		end
		
		if character_id == "val_smart_terrain_7_3_bandit_mechanic_stalker" then
			local res = dialog_list:add("aftermarket_exchange_insider_bandit")
		end
		
		if character_id == "mar_base_stalker_tech" then
			local res = dialog_list:add("aftermarket_exchange_insider_cs")
		end
		
		if character_id == "esc_smart_terrain_5_7_loner_mechanic_stalker" then
			local res = dialog_list:add("aftermarket_exchange_insider_loner")
		end
		
		if character_id == "army_south_mechan_mlr" then
			local res = dialog_list:add("aftermarket_exchange_insider_military")
		end
		
		if character_id == "cit_killers_merc_mechanic_stalker" then
			local res = dialog_list:add("aftermarket_exchange_insider_mercenary")
		end
		
		if character_id == "agr_smart_terrain_1_6_army_mechanic_stalker" then
			local res = dialog_list:add("aftermarket_exchange_insider_military")
		end
		
		if character_id == "jup_b217_stalker_tech" then
			local res = dialog_list:add("aftermarket_exchange_insider_loner")
		end
		
		if character_id == "jup_b6_scientist_tech" then
			local res = dialog_list:add("aftermarket_exchange_insider_ecolog")
		end
		
		if character_id == "jup_cont_mech_bandit" then
			local res = dialog_list:add("aftermarket_exchange_insider_bandit")
		end
		
		if character_id == "mechanic_monolith_jup_depo" then
			local res = dialog_list:add("aftermarket_exchange_insider_monolith")
		end
		
		if character_id == "bar_visitors_stalker_mechanic" then
			local res = dialog_list:add("aftermarket_exchange_insider_duty")
		end
		
		if character_id == "zat_stancia_mech_merc" then
			local res = dialog_list:add("aftermarket_exchange_insider_mercenary")
		end
		
		if character_id == "zat_tech_mlr" then
			local res = dialog_list:add("aftermarket_exchange_insider_loner")
		end
		
		if character_id == "zat_a2_stalker_mechanic" then
			local res = dialog_list:add("aftermarket_exchange_insider_loner")
		end
		
	end)
end
	